version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "8080:8000"
    environment:
      DB_HOST: db
      DB_NAME: labdb
      DB_USER: labuser
      DB_PASS: labpass
      WORKER_URL: http://worker:8001/work
    depends_on:
      - db
      - worker

  worker:
    build: ./worker
    ports:
      - "8002:8001"
    environment:
      SLEEP_SECONDS: "6"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
